### ISSUE TITLE
Help with the code

### ISSUE THREAD

**Issue by JuliaKunsch** [mihasm/Python-BEM#1]
Hello, firstly, congratulations on the code development!
I would like to know how to execute it directly through the script, could you give me an example?

Thank you for your help.

**Comment by mihasm** [comment]
Hi!

The easiest way is to download the source code,

Create a "foils" directory manually in the root directory (same level as test or UI f.e.). This is created automatically if the main entry script bem.py is ran.

After that go to tests folder and run the "test_just_calculate.py".

All of the input arguments for the calculation, along with the turbine geometry data, and the airfoils data (geometry and the Cl/alpha Cd/alpha curves), are stored in a json file, for which an example is karlsen.bem. It is structured so that it is pretty self-explanatory, so creating cusotm JSON files for this data shouldnt be a problem if needed.

Everytime you create a custom geometry from the main GUI app, it can be saved from File/Save, and this creates another .bem file, which can be used to run the analysis using the calculate_power_3d() function.

You can also try changing the input parameters and checking what changes in the output .bem JSON file, to see, which parameters are mapped to which numbers, for example, or for checking what the logic of storing the numpy arrays of lift/drag curves and turbine geometry.

I hope this makes sense.

Best
